name: SimpleOnline

main: Online\Main

api: 4.0.0

version: 1.0.0

author: SexxRetacted

commands: 
  online:
    description: "Online Players Command"
    permission: online.cmd
    
permissions:
  online.cmd:
    description: "online permission"
    default: true